### PR TITLE
[WIP] Upgrade braces

### PR DESCRIPTION
**Pull request by mobilutz**
https://www.npmjs.com/advisories/786

### CODE REVIEW

**Comment by mobilutz** [comment]
@jonschlinkert It looks like in a braces version between 0.1.4 and 2.3.1 the handling of one braces value has been changed. I am not too familiar with what `expand-braces` is used for, and if the failing specs are even worth to look at in detail.

Could you please take a look at this and give some feedback.

Thanks

**Comment by Teamop** [comment]
@jonschlinkert the cases failed mostly for brace with single item changes
```
--v1.8
// default
braces('a{b}c');
//=> ['abc']
// if with option
braces('a{b}c', {bash: true});
//=> ['a{b}c']

--v2
// default, seems no option to control this behavior
console.log(braces.expand('a{b}c'));
//=> ['a{b}c']
```

**Comment by jonschlinkert** [comment]
> the cases failed mostly for brace with single item changes

1. This is correct behavior according to every convention for brace expansion that I've found, and it's in the unit tests
1. This is completely unrelated to this issue. If you have a question or want to achieve something that you're not able to figure out from the docs, then please create a new issue and I'd be happy to help. 

> It looks like in a braces version between 0.1.4 and 2.3.1 the handling of one braces value has been changed.

Thank you for the PR @mobilutz! If it's not too much trouble, could you update the `.travis.yml` config to whatever versions are specified in the `braces` travis config, so that we can ensure unit tests are passing? Then I'll merge this in and publish a patch ASAP! Thanks!

(edit: and I will take care of fixing the tests)

**Comment by Teamop** [comment]
@jonschlinkert could you elaborate a bit? thanks
From the Travis log, and [v1.8 default setting](https://github.com/micromatch/braces/tree/1.8.5#optionsbash) and [current master 2.3.2 for expanding with single item](https://github.com/micromatch/braces/tree/master#escaping)
```
1) given an array of patterns with braces
       braces
         should work with one value:
      AssertionError: expected [ 'a{b}c', 'a/b/c{d}e' ] to equal [ 'abc', 'a/b/cde' ] (at '0', A has 'a{b}c' and B has 'abc')
      + expected - actual
       [
      -  "a{b}c"
      -  "a/b/c{d}e"
      +  "abc"
      +  "a/b/cde"
       ]
      
      at Proxy.fail (node_modules/should/lib/assertion.js:228:17)
      at Proxy.prop.(anonymous function) (node_modules/should/lib/assertion.js:69:14)
      at Context.<anonymous> (test.js:32:45)
  2) given an array of patterns with braces
       braces
         should work with nested non-sets:
      AssertionError: expected [ '{a-b}', '{a-c}', '{a-d}', 'a' ] to equal [ 'a-b', 'a-c', 'a-d', 'a' ] (at '0', A has '{a-b}' and B has 'a-b')
      + expected - actual
       [
      -  "{a-b}"
      -  "{a-c}"
      -  "{a-d}"
      +  "a-b"
      +  "a-c"
      +  "a-d"
         "a"
       ]
      
      at Proxy.fail (node_modules/should/lib/assertion.js:228:17)
      at Proxy.prop.(anonymous function) (node_modules/should/lib/assertion.js:69:14)
      at Context.<anonymous> (test.js:36:57)
  3) given an array of patterns with braces
       braces
         should expand sets:
      AssertionError: expected [ 'a/x/c{d}e', 'a/y/c{d}e', 'a/b/c/x', 'a/b/c/y' ] to equal [ 'a/x/cde', 'a/y/cde', 'a/b/c/x', 'a/b/c/y' ] (at '0', A has 'a/x/c{d}e' and B has 'a/x/cde')
      + expected - actual
       [
      -  "a/x/c{d}e"
      -  "a/y/c{d}e"
      +  "a/x/cde"
      +  "a/y/cde"
         "a/b/c/x"
         "a/b/c/y"
       ]
      
      at Proxy.fail (node_modules/should/lib/assertion.js:228:17)
      at Proxy.prop.(anonymous function) (node_modules/should/lib/assertion.js:69:14)
      at Context.<anonymous> (test.js:44:55)
  4) given an array of patterns with braces
       braces
         should throw an error when imbalanced braces are found.:
     AssertionError: expected [Function] to throw exception
      at Proxy.fail (node_modules/should/lib/assertion.js:228:17)
      at Proxy.prop.(anonymous function) (node_modules/should/lib/assertion.js:69:14)
      at Context.<anonymous> (test.js:50:22)
  5) given an array of patterns with braces
       should expand a combination of nested sets and ranges.
         should expand sets:
      AssertionError: expected [
  'a/x/c{d}e',
  'a/1/c{d}e',
  'a/2/c{d}e',
  'a/3/c{d}e',
  'a/4/c{d}e',
  'a/5/c{d}e',
  'a/y/c{d}e'
] to equal [
  'a/x/cde',
  'a/1/cde',
  'a/y/cde',
  'a/2/cde',
  'a/3/cde',
  'a/4/cde',
  'a/5/cde'
] (at '0', A has 'a/x/c{d}e' and B has 'a/x/cde')
      + expected - actual
       [
      -  "a/x/c{d}e"
      -  "a/1/c{d}e"
      -  "a/2/c{d}e"
      -  "a/3/c{d}e"
      -  "a/4/c{d}e"
      -  "a/5/c{d}e"
      -  "a/y/c{d}e"
      +  "a/x/cde"
      +  "a/1/cde"
      +  "a/y/cde"
      +  "a/2/cde"
      +  "a/3/cde"
      +  "a/4/cde"
      +  "a/5/cde"
       ]
      
      at Proxy.fail (node_modules/should/lib/assertion.js:228:17)
      at Proxy.prop.(anonymous function) (node_modules/should/lib/assertion.js:69:14)
      at Context.<anonymous> (test.js:85:47)
```

**Comment by jonschlinkert** [comment]
@Teamop I didn't read your last message, it was deleted. Please create a new issue as I requested in my last comment.

Also, if the unit tests are failing, it's because the unit tests are wrong in this library. Braces is correct per specification, and there are comprehensive unit tests as such. If you see something that is wrong _in braces_, and you can point to the specification that shows that the behavior is wrong, then please create an issue on braces.

**Comment by Teamop** [comment]
@jonschlinkert ok, not sure why it was deleted... thanks again

**Comment by Teamop** [comment]
@jonschlinkert ohh.. I just saw the recent message, so the test cases are wrong, that's the reason why the cases failed. I'm not familiar with braces expansion, so thanks for your explanation.

**Comment by mobilutz** [comment]
@jonschlinkert I updated `.travis.yml` to the same content as braces.

Now node 0.10 and 0.12 are failing completely because of mocha - the version 5.2.0 of mocha requires node >4: https://github.com/mochajs/mocha/blob/v5.2.0/package.json#L452
The rest show the same errors as before.

**Comment by mobilutz** [comment]
@jonschlinkert I downgrade mocha to the same version of braces, and now all travis runs fail at the same points.

**Comment by jonschlinkert** [comment]
You should be able to upgrade the lock file and mocha. Tests will fail, I’ll fix the tests.

**Comment by stramunin** [comment]
When to wait for updates?

**Comment by gregorycraske** [comment]
Bump! My team are waiting on these transitive dependencies of Karma to be uplifted, which is currently failing audit. Is there anything specific you're waiting on here?

**Comment by mobilutz** [comment]
@gregorycraske You can use yarns `resolutions` to upgrade braces manually:
https://yarnpkg.com/lang/en/docs/selective-version-resolutions/

We have this in our package.json
```
  "resolutions": {
    "braces": "^2.3.2"
  }
```

Of course and upgrade hear would be better, but with this you can have a correct audit and secure system.

**Comment by hackeo1** [comment]
Any update with the travis tests?

**Comment by mobilutz** [comment]
@jonschlinkert I am cleaning up all my old GitHub PullRequests and want to ask how I can support further here.

I currently cannot find the TravisCI runs at all, and don't know how I can push this change forward.

**Pull request closed without merging**
